language: python
python: "3.7"
os: linux
dist: xenial
env: BFM_SEEDMINER_AUTOLAUNCHER="static/bfm_seedminer_autolauncher.py"

install:
  - pip install pyflakes pytest
script:
  - pyflakes $BFM_SEEDMINER_AUTOLAUNCHER
  - pytest